version: "3"
services:
  frontend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8081:8080
    volumes:
      - ./app:/bindmount:rw
      # The volume is effectively hiding node_modules from the host and must be in this order
      - node_modules:/src/node_modules
      - ./npmlogs:/root/.npm/_logs/
    command: ["npm", "run", "dev"]
  backend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8082:3000
    volumes:
      - ./app:/bindmount:rw
      # The volume is effectively hiding node_modules from the host and must be in this order
      - node_modules:/src/node_modules
      - ./npmlogs:/root/.npm/_logs/
    command: ["npm", "run", "serverdev"]
volumes:
  node_modules:
